# Generated by Django 5.2.9 on 2025-12-16 10:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('login_attempts', models.IntegerField(default=0)),
                ('locked_out', models.BooleanField(default=False)),
                ('locked_out_expiration', models.DateTimeField(default=datetime.datetime(2025, 12, 16, 11, 0, 29, 616871, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='5bde756acd2c6c325d2c123f441f221b4b02d16c0f873619564cd2f7bb72bfa3', max_length=64)),
                ('otp_expiration', models.DateTimeField(default=datetime.datetime(2025, 12, 16, 10, 55, 29, 616061, tzinfo=datetime.timezone.utc))),
                ('locked_out', models.BooleanField(default=False)),
                ('locked_out_expiration', models.DateTimeField(default=datetime.datetime(2025, 12, 16, 10, 55, 29, 616549, tzinfo=datetime.timezone.utc))),
                ('login_attempts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
