# Generated by Django 5.1.2 on 2025-12-16 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockedip',
            name='locked_out_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 11, 2, 3, 545460, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locked_out_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 10, 57, 3, 545055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(default='bc42004e386a720732fba765ffcf375b6d83590fe0e8df5824f123692048c554', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 10, 57, 3, 544448, tzinfo=datetime.timezone.utc)),
        ),
    ]
