# Generated by Django 5.1.2 on 2025-12-16 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_lockedip_locked_out_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockedip',
            name='locked_out_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 12, 42, 45, 341952, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locked_out_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 12, 37, 45, 341768, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(default='1062256647d8e1faffae696ed2428d4057c7ceb1150b6fe2a5c7a48d15f5e6b5', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 12, 37, 45, 341390, tzinfo=datetime.timezone.utc)),
        ),
    ]
