# Generated by Django 5.2.9 on 2025-12-19 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_lockedip_locked_out_expiration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='LockedIP',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='locked_out',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='locked_out_expiration',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='login_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_expiration',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
