# Generated by Django 5.2.9 on 2025-12-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_lockedip_remove_userprofile_locked_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
