# Generated by Django 5.1.6 on 2025-05-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(default="Hello Jeremy,\n\nI'd like to schedule an interview with you...\n\n")),
            ],
        ),
    ]
