# Generated by Django 5.1.6 on 2026-02-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zip_code', models.IntegerField()),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
