# Generated by Django 5.1.6 on 2026-02-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_location_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='zip_code',
        ),
    ]
