# Generated by Django 5.1.6 on 2026-02-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='hour',
            field=models.DateTimeField(),
        ),
    ]
